/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budget;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ROHIT
 */
public class WithdrawFrame extends javax.swing.JFrame {

    /**
     * Creates new form DepositFrame
     */
    public WithdrawFrame() {
        initComponents();
    } 
    int id; 
    public WithdrawFrame(int id) {
        initComponents();
        this.id = id;
        
        setVisible(true);
        setLocationRelativeTo(null);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDateWithdraw = new javax.swing.JTextField();
        txtAmountWithdraw = new javax.swing.JTextField();
        lblDateWithdraw = new javax.swing.JLabel();
        lbAmountWithdraw = new javax.swing.JLabel();
        btnSaveWithdraw = new javax.swing.JButton();
        btnCancelWithdraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Withdraw");
        setResizable(false);

        txtDateWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateWithdrawActionPerformed(evt);
            }
        });

        txtAmountWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountWithdrawActionPerformed(evt);
            }
        });

        lblDateWithdraw.setText("Date :");

        lbAmountWithdraw.setText("Amount :");

        btnSaveWithdraw.setText("Save");
        btnSaveWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveWithdrawActionPerformed(evt);
            }
        });

        btnCancelWithdraw.setText("Cancel");
        btnCancelWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelWithdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDateWithdraw)
                                .addGap(18, 18, 18)
                                .addComponent(txtDateWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbAmountWithdraw)
                                .addGap(18, 18, 18)
                                .addComponent(txtAmountWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnSaveWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelWithdraw)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateWithdraw)
                    .addComponent(txtDateWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmountWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAmountWithdraw))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveWithdraw)
                    .addComponent(btnCancelWithdraw))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateWithdrawActionPerformed

    private void btnCancelWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelWithdrawActionPerformed

        dispose();
    }//GEN-LAST:event_btnCancelWithdrawActionPerformed

    private void btnSaveWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveWithdrawActionPerformed
        DbHandler db = new DbHandler();
        long bal = db.checkBalance(id);
        long amt = Long.parseLong(txtAmountWithdraw.getText());
        
        if(bal>=amt){
            bal-=amt;
            int r = db.withdraw(id, txtDateWithdraw.getText(), "Debit",amt , bal);
            if(r>0){
                JOptionPane.showMessageDialog(new JDialog(),"Transaction successful");
                dispose();
            }
        }else{
            JOptionPane.showMessageDialog(new JDialog(),"Issufficient balance "+id);
        }
       
    }//GEN-LAST:event_btnSaveWithdrawActionPerformed

    private void txtAmountWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountWithdrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WithdrawFrame df = new WithdrawFrame();
                df.setVisible(true);
                df.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelWithdraw;
    private javax.swing.JButton btnSaveWithdraw;
    private javax.swing.JLabel lbAmountWithdraw;
    private javax.swing.JLabel lblDateWithdraw;
    private javax.swing.JTextField txtAmountWithdraw;
    private javax.swing.JTextField txtDateWithdraw;
    // End of variables declaration//GEN-END:variables
}
